ALTER TABLE channels
    MODIFY paused_at DATETIME(6) NULL;

ALTER TABLE channel_health_observations
    MODIFY observed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE channel_pause_events
    MODIFY event_type ENUM('PAUSE','RESUME','HEALTH_FAILURE','MAINTENANCE_START','MAINTENANCE_END') NOT NULL,
    MODIFY created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
