ALTER TABLE bulk_sendings MODIFY COLUMN task_status ENUM('PENDING','RUNNING','PAUSED','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE bulk_sendings ADD COLUMN batch_key VARCHAR(64) NULL;
ALTER TABLE bulk_sendings ADD COLUMN source_file_name VARCHAR(255) NULL;
ALTER TABLE bulk_sendings ADD COLUMN valid_count INT NOT NULL DEFAULT 0;
ALTER TABLE bulk_sendings ADD COLUMN invalid_count INT NOT NULL DEFAULT 0;
ALTER TABLE bulk_sendings ADD COLUMN running_count INT NOT NULL DEFAULT 0;
ALTER TABLE bulk_sendings ADD COLUMN completed_count INT NOT NULL DEFAULT 0;
ALTER TABLE bulk_sendings ADD COLUMN cancelled_count INT NOT NULL DEFAULT 0;
ALTER TABLE bulk_sendings ADD COLUMN failure_reason VARCHAR(500) NULL;
ALTER TABLE bulk_sendings ADD COLUMN control_reason VARCHAR(500) NULL;
ALTER TABLE bulk_sendings ADD COLUMN import_snapshot_json JSON NULL;
ALTER TABLE bulk_sendings ADD UNIQUE KEY uk_bulk_sendings_batch_key (tenant_id, batch_key);

ALTER TABLE bulk_sending_items MODIFY COLUMN send_status ENUM('PENDING','SENT','DELIVERED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE bulk_sending_items ADD COLUMN tenant_id BIGINT UNSIGNED NULL;
ALTER TABLE bulk_sending_items ADD COLUMN item_tracking_id VARCHAR(80) NULL;
ALTER TABLE bulk_sending_items ADD COLUMN row_no INT NULL;
ALTER TABLE bulk_sending_items ADD COLUMN mobile_hash CHAR(64) NULL;
ALTER TABLE bulk_sending_items ADD COLUMN message_id VARCHAR(64) NULL;
ALTER TABLE bulk_sending_items ADD COLUMN message_task_id BIGINT UNSIGNED NULL;
ALTER TABLE bulk_sending_items ADD COLUMN submit_id BIGINT UNSIGNED NULL;
ALTER TABLE bulk_sending_items ADD COLUMN validation_status ENUM('VALID','INVALID') NOT NULL DEFAULT 'VALID';
ALTER TABLE bulk_sending_items ADD COLUMN validation_reason VARCHAR(255) NULL;
ALTER TABLE bulk_sending_items ADD COLUMN cost DECIMAL(10,4) NOT NULL DEFAULT 0;
ALTER TABLE bulk_sending_items ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE bulk_sending_items ADD UNIQUE KEY uk_bulk_item_tracking (item_tracking_id);
ALTER TABLE bulk_sending_items ADD UNIQUE KEY uk_bulk_item_row (bulk_id, row_no);
ALTER TABLE bulk_sending_items ADD KEY idx_bulk_item_task (message_task_id);
ALTER TABLE bulk_sending_items ADD KEY idx_bulk_item_status (bulk_id, send_status);
