package com.ycsopen.sms.core.common.security.persistence;

import com.ycsopen.sms.core.common.security.envelope.EnvelopeCodec;
import com.ycsopen.sms.core.common.security.envelope.ProtectionContext;
import com.ycsopen.sms.core.common.security.key.BlindIndexPort;
import com.ycsopen.sms.core.common.security.key.KeyHealth;
import com.ycsopen.sms.core.common.security.key.KeyProtectionPort;
import com.ycsopen.sms.core.common.security.key.VersionedBlindIndex;
import com.ycsopen.sms.core.common.security.key.WrappedDataKey;
import com.ycsopen.sms.core.domain.entity.BlacklistEntry;
import java.security.SecureRandom;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DataJpaTest
@ActiveProfiles("test")
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class BlacklistEntryProtectionAdapterTest {

    private static final String MOBILE = "13800138000";
    private static final String KEY_REFERENCE = "field-kek.v1";
    private static final VersionedBlindIndex RETIRING =
            new VersionedBlindIndex(1, sequence(32, 11));
    private static final VersionedBlindIndex ACTIVE =
            new VersionedBlindIndex(2, sequence(32, 31));

    @Autowired
    JdbcTemplate jdbc;

    @Autowired
    PlatformTransactionManager transactionManager;

    private BlacklistEntryProtectionAdapter adapter;

    @BeforeEach
    void resetSchema() {
        jdbc.update("DELETE FROM blacklist_entries");
        jdbc.execute("DROP TABLE IF EXISTS ycs_crypto_blind_indexes");
        jdbc.execute("DROP TABLE IF EXISTS ycs_crypto_key_references");
        jdbc.execute("""
                CREATE TABLE ycs_crypto_key_references (
                    purpose VARCHAR(48) NOT NULL,
                    key_version BIGINT NOT NULL,
                    provider_id VARCHAR(32) NOT NULL,
                    provider_key_reference VARCHAR(128) NOT NULL,
                    key_state VARCHAR(24) NOT NULL,
                    PRIMARY KEY (purpose, key_version)
                )
                """);
        jdbc.execute("""
                CREATE TABLE ycs_crypto_blind_indexes (
                    blind_index_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    target_type VARCHAR(64) NOT NULL,
                    legacy_row_id BIGINT NOT NULL,
                    field_id VARCHAR(64) NOT NULL,
                    key_purpose VARCHAR(48) NOT NULL,
                    key_version BIGINT NOT NULL,
                    index_value VARCHAR(53) NOT NULL,
                    index_status VARCHAR(16) NOT NULL,
                    original_row_digest BINARY(32) NOT NULL,
                    row_binding_digest BINARY(32),
                    UNIQUE (target_type, legacy_row_id, field_id, key_version)
                )
                """);
        insertKey(1, "RETIRING");
        insertKey(2, "ACTIVE");
        jdbc.update("INSERT INTO ycs_crypto_key_references "
                + "(purpose,key_version,provider_id,provider_key_reference,key_state) "
                + "VALUES ('FIELD_ENCRYPTION_KEK',1,'pkcs11',?,'ACTIVE')", KEY_REFERENCE);
        ProtectedFieldCodec codec = new ProtectedFieldCodec(
                new EnvelopeCodec(), new RecordingKeyPort(), new FixedSecureRandom(), KEY_REFERENCE);
        adapter = new BlacklistEntryProtectionAdapter(codec, new RecordingBlindIndexPort(), jdbc,
                new TransactionTemplate(transactionManager), new FixedSecureRandom());
    }

    @Test
    void createDisableAndDeleteAtomicallyMoveRowAndEveryBindingTogether() {
        long id = adapter.create(17L, MOBILE, BlacklistEntry.ListType.WHITE,
                BlacklistEntry.Source.MANUAL, "synthetic");

        assertThat(jdbc.queryForObject("SELECT status FROM blacklist_entries WHERE id=?",
                String.class, id)).isEqualTo("ACTIVE");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ycs_crypto_blind_indexes "
                + "WHERE legacy_row_id=?", Long.class, id)).isEqualTo(2);
        assertThat(jdbc.queryForList("SELECT key_version,index_status,OCTET_LENGTH(row_binding_digest) "
                + "AS binding_bytes FROM ycs_crypto_blind_indexes WHERE legacy_row_id=? "
                + "ORDER BY key_version", id)).containsExactly(
                java.util.Map.of("KEY_VERSION", 1L, "INDEX_STATUS", "RETIRING",
                        "BINDING_BYTES", 32L),
                java.util.Map.of("KEY_VERSION", 2L, "INDEX_STATUS", "ACTIVE",
                        "BINDING_BYTES", 32L));

        adapter.disable(id);

        assertThat(jdbc.queryForObject("SELECT status FROM blacklist_entries WHERE id=?",
                String.class, id)).isEqualTo("DISABLED");
        byte[] envelope = jdbc.queryForObject(
                "SELECT mobile_encrypted FROM blacklist_entries WHERE id=?", byte[].class, id);
        String locator = jdbc.queryForObject(
                "SELECT mobile_hash FROM blacklist_entries WHERE id=?", String.class, id);
        byte[] original = sha256(locator);
        byte[] expected = BlindIndexLookupService.blacklistBinding(id, 17L,
                BlacklistEntry.ListType.WHITE, BlacklistEntry.Status.DISABLED, envelope, original);
        assertThat(jdbc.query("SELECT row_binding_digest FROM ycs_crypto_blind_indexes "
                        + "WHERE legacy_row_id=?", (rs, row) -> rs.getBytes(1), id))
                .allSatisfy(binding -> assertThat(binding).containsExactly(expected));

        adapter.delete(id);

        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM blacklist_entries WHERE id=?",
                Long.class, id)).isZero();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ycs_crypto_blind_indexes "
                + "WHERE legacy_row_id=?", Long.class, id)).isZero();
    }

    @Test
    void missingKeyMetadataRollsBackRowAndAllEarlierIndexWrites() {
        jdbc.update("DELETE FROM ycs_crypto_key_references WHERE key_version=2");

        assertRejected(() -> adapter.create(null, MOBILE, BlacklistEntry.ListType.BLACK,
                BlacklistEntry.Source.MANUAL, null));

        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM blacklist_entries", Long.class)).isZero();
        assertThat(jdbc.queryForObject(
                "SELECT COUNT(*) FROM ycs_crypto_blind_indexes", Long.class)).isZero();
    }

    @Test
    void extraQueryableKeyNotReturnedByProviderFailsBeforeAnyBusinessWrite() {
        insertKey(3, "RETIRING");

        assertRejected(() -> adapter.create(null, MOBILE, BlacklistEntry.ListType.BLACK,
                BlacklistEntry.Source.MANUAL, null));

        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM blacklist_entries", Long.class)).isZero();
        assertThat(jdbc.queryForObject(
                "SELECT COUNT(*) FROM ycs_crypto_blind_indexes", Long.class)).isZero();
    }

    @Test
    void staleIdentityPolicyEnvelopeOrMetadataFailsClosedWithoutPartialDelete() {
        assertStaleDeleteRejected("UPDATE blacklist_entries SET mobile_hash='changed' WHERE id=?");
        assertStaleDeleteRejected("UPDATE blacklist_entries SET tenant_id=18 WHERE id=?");
        assertStaleDeleteRejected("UPDATE blacklist_entries SET list_type='BLACK' WHERE id=?");
        assertStaleDeleteRejected("UPDATE blacklist_entries SET status='DISABLED' WHERE id=?");
        assertStaleDeleteRejected("UPDATE blacklist_entries SET mobile_encrypted=X'0102' WHERE id=?");
        assertStaleDeleteRejected("UPDATE ycs_crypto_blind_indexes SET row_binding_digest=X'00' "
                + "WHERE legacy_row_id=?");
    }

    private void assertStaleDeleteRejected(String mutation) {
        long id = adapter.create(17L, MOBILE, BlacklistEntry.ListType.WHITE,
                BlacklistEntry.Source.MANUAL, null);
        jdbc.update(mutation, id);
        long indexes = jdbc.queryForObject("SELECT COUNT(*) FROM ycs_crypto_blind_indexes "
                + "WHERE legacy_row_id=?", Long.class, id);

        assertRejected(() -> adapter.delete(id));

        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM blacklist_entries WHERE id=?",
                Long.class, id)).isOne();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ycs_crypto_blind_indexes "
                + "WHERE legacy_row_id=?", Long.class, id)).isEqualTo(indexes);
    }

    private void assertRejected(Runnable operation) {
        assertThatThrownBy(operation::run)
                .isExactlyInstanceOf(IllegalStateException.class)
                .hasMessage(BlacklistEntryProtectionAdapter.SANITIZED_FAILURE)
                .hasNoCause();
    }

    private void insertKey(long version, String state) {
        jdbc.update("INSERT INTO ycs_crypto_key_references "
                + "(purpose,key_version,provider_id,provider_key_reference,key_state) "
                + "VALUES ('MOBILE_BLIND_INDEX',?,'pkcs11',?,?)",
                version, "mobile-v" + version, state);
    }

    private static byte[] sha256(String value) {
        try {
            return java.security.MessageDigest.getInstance("SHA-256")
                    .digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        } catch (Exception failure) {
            throw new AssertionError(failure);
        }
    }

    private static byte[] sequence(int length, int seed) {
        byte[] value = new byte[length];
        for (int index = 0; index < length; index++) {
            value[index] = (byte) (seed + index);
        }
        return value;
    }

    private static final class FixedSecureRandom extends SecureRandom {
        private long nextId = 100;
        private int invocation;

        @Override
        public long nextLong() {
            return nextId++;
        }

        @Override
        public void nextBytes(byte[] bytes) {
            invocation++;
            for (int index = 0; index < bytes.length; index++) {
                bytes[index] = (byte) (invocation * 17 + index);
            }
        }
    }

    private static final class RecordingKeyPort implements KeyProtectionPort {
        @Override
        public WrappedDataKey wrap(byte[] dataEncryptionKey, byte[] authenticatedHeader,
                                   ProtectionContext semanticContext) {
            return new WrappedDataKey(KEY_REFERENCE, new byte[12], new byte[48]);
        }

        @Override
        public byte[] unwrap(WrappedDataKey wrappedDataKey, byte[] authenticatedHeader,
                             ProtectionContext semanticContext) {
            throw new UnsupportedOperationException();
        }

        @Override
        public KeyHealth health() {
            return new KeyHealth(KeyHealth.Status.READY);
        }
    }

    private static final class RecordingBlindIndexPort implements BlindIndexPort {
        @Override
        public OrderedIndexes writeIndexes(String normalizedMobile, Context context) {
            if (!MOBILE.equals(normalizedMobile)) {
                throw new IllegalStateException("unexpected test input");
            }
            return new OrderedIndexes(List.of(RETIRING, ACTIVE));
        }

        @Override
        public OrderedIndexes queryIndexes(String normalizedMobile, Context context) {
            return writeIndexes(normalizedMobile, context);
        }

        @Override
        public KeyHealth health() {
            return new KeyHealth(KeyHealth.Status.READY);
        }
    }
}
