package com.ycsopen.sms.core.common.security.persistence;

import com.ycsopen.sms.core.common.security.key.BlindIndexPort;
import com.ycsopen.sms.core.common.security.key.VersionedBlindIndex;
import com.ycsopen.sms.core.domain.entity.BlacklistEntry;
import com.ycsopen.sms.core.repository.BlacklistEntryRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@DataJpaTest
@ActiveProfiles("test")
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class BlindIndexLookupServiceTest {

    private static final long TENANT_ID = 17L;
    private static final String MOBILE = "13800138000";
    private static final VersionedBlindIndex RETIRING =
            new VersionedBlindIndex(1, sequence(0x11));
    private static final VersionedBlindIndex ACTIVE =
            new VersionedBlindIndex(2, sequence(0x22));
    private static final BlindIndexPort.OrderedIndexes INDEXES =
            new BlindIndexPort.OrderedIndexes(List.of(RETIRING, ACTIVE));

    @Autowired
    JdbcTemplate jdbc;

    @BeforeEach
    void resetSchema() {
        jdbc.update("DELETE FROM blacklist_entries WHERE id BETWEEN 931000 AND 931999");
        jdbc.execute("DROP TABLE IF EXISTS ycs_crypto_blind_indexes");
        jdbc.execute("DROP TABLE IF EXISTS ycs_crypto_key_references");
        jdbc.execute("DROP TABLE IF EXISTS ycs_crypto_migration_targets");
        jdbc.execute("""
                CREATE TABLE ycs_crypto_migration_targets (
                    target_type VARCHAR(64) PRIMARY KEY,
                    target_state VARCHAR(16) NOT NULL,
                    legacy_fallback_allowed BOOLEAN NOT NULL
                )
                """);
        jdbc.execute("""
                CREATE TABLE ycs_crypto_key_references (
                    purpose VARCHAR(48) NOT NULL,
                    key_version BIGINT NOT NULL,
                    key_state VARCHAR(24) NOT NULL,
                    PRIMARY KEY (purpose, key_version)
                )
                """);
        jdbc.execute("""
                CREATE TABLE ycs_crypto_blind_indexes (
                    blind_index_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    target_type VARCHAR(64) NOT NULL,
                    legacy_row_id BIGINT NOT NULL,
                    field_id VARCHAR(64) NOT NULL,
                    key_purpose VARCHAR(48) NOT NULL,
                    key_version BIGINT NOT NULL,
                    index_value VARCHAR(53) NOT NULL,
                    index_status VARCHAR(16) NOT NULL,
                    original_row_digest BINARY(32) NOT NULL
                )
                """);
        jdbc.update("INSERT INTO ycs_crypto_migration_targets VALUES (?, ?, ?)",
                "BLACKLIST_ENTRY", "BACKFILLED", true);
        insertKey(1, "RETIRING");
        insertKey(2, "ACTIVE");
    }

    @Test
    void unionsActiveAndRetiringMetadataDeduplicatesBindingsAndAppliesWhitelistPrecedence() {
        insertBlacklist(931001L, null, "locator-system", "BLACK");
        insertMetadata(931001L, RETIRING, "RETIRING", repeated(0x31));
        insertMetadata(931001L, ACTIVE, "ACTIVE", repeated(0x31));

        BlacklistEntryRepository legacy = mock(BlacklistEntryRepository.class);
        when(legacy.findSystemLegacyCompatibilityMatches(rawDigestHex(), BlacklistEntry.Status.ACTIVE))
                .thenReturn(List.of());
        BlacklistEntryRepository.LookupProjection whitelist =
                projection(931002L, TENANT_ID, BlacklistEntry.ListType.WHITE);
        when(legacy.findTenantLegacyCompatibilityMatches(
                rawDigestHex(), TENANT_ID, BlacklistEntry.Status.ACTIVE))
                .thenReturn(List.of(whitelist));

        BlindIndexLookupService.BlacklistLookupResult result = service(legacy)
                .lookupBlacklist(TENANT_ID, token(), BlacklistEntry.Status.ACTIVE);

        assertThat(result.tenantWhitelist()).isTrue();
        assertThat(result.blocked()).isFalse();
        verify(legacy).findSystemLegacyCompatibilityMatches(
                rawDigestHex(), BlacklistEntry.Status.ACTIVE);
        verify(legacy).findTenantLegacyCompatibilityMatches(
                rawDigestHex(), TENANT_ID, BlacklistEntry.Status.ACTIVE);
    }

    @Test
    void permitsLegacyOnlyBeforeCheckpointCompletionAndUsesMetadataAfterCompletion() {
        BlacklistEntryRepository legacy = mock(BlacklistEntryRepository.class);
        when(legacy.findSystemLegacyCompatibilityMatches(rawDigestHex(), BlacklistEntry.Status.ACTIVE))
                .thenReturn(List.of());
        BlacklistEntryRepository.LookupProjection tenantBlacklist =
                projection(931003L, TENANT_ID, BlacklistEntry.ListType.BLACK);
        when(legacy.findTenantLegacyCompatibilityMatches(
                rawDigestHex(), TENANT_ID, BlacklistEntry.Status.ACTIVE))
                .thenReturn(List.of(tenantBlacklist));
        BlindIndexLookupService service = service(legacy);

        assertThat(service.lookupBlacklist(TENANT_ID, token(), BlacklistEntry.Status.ACTIVE).blocked())
                .isTrue();

        reset(legacy);
        jdbc.update("UPDATE ycs_crypto_migration_targets "
                + "SET target_state = 'COMPLETE', legacy_fallback_allowed = FALSE "
                + "WHERE target_type = 'BLACKLIST_ENTRY'");
        BlindIndexLookupService.BlacklistLookupResult completed = service.lookupBlacklist(
                TENANT_ID, token(), BlacklistEntry.Status.ACTIVE);
        assertThat(completed.blocked()).isFalse();
        verify(legacy, never()).findSystemLegacyCompatibilityMatches(
                rawDigestHex(), BlacklistEntry.Status.ACTIVE);
        verify(legacy, never()).findTenantLegacyCompatibilityMatches(
                rawDigestHex(), TENANT_ID, BlacklistEntry.Status.ACTIVE);

        insertBlacklist(931004L, TENANT_ID, "locator-tenant", "BLACK");
        insertMetadata(931004L, RETIRING, "RETIRING", repeated(0x41));
        insertMetadata(931004L, ACTIVE, "ACTIVE", repeated(0x41));
        assertThat(service.lookupBlacklist(TENANT_ID, token(), BlacklistEntry.Status.ACTIVE).blocked())
                .isTrue();
        verify(legacy, never()).findSystemLegacyCompatibilityMatches(
                rawDigestHex(), BlacklistEntry.Status.ACTIVE);
    }

    @Test
    void failsClosedForMissingKeyStateOrphanAndConflictingDuplicateBinding() {
        BlacklistEntryRepository legacy = mock(BlacklistEntryRepository.class);
        BlindIndexLookupService service = service(legacy);

        jdbc.update("DELETE FROM ycs_crypto_key_references WHERE key_version = 2");
        assertSanitized(() -> service.lookupBlacklist(TENANT_ID, token(), BlacklistEntry.Status.ACTIVE));

        insertKey(2, "ACTIVE");
        insertMetadata(931099L, ACTIVE, "ACTIVE", repeated(0x51));
        assertSanitized(() -> service.lookupBlacklist(TENANT_ID, token(), BlacklistEntry.Status.ACTIVE));

        jdbc.update("DELETE FROM ycs_crypto_blind_indexes");
        insertBlacklist(931005L, TENANT_ID, "locator-conflict", "BLACK");
        insertMetadata(931005L, RETIRING, "RETIRING", repeated(0x61));
        insertMetadata(931005L, ACTIVE, "ACTIVE", repeated(0x62));
        assertSanitized(() -> service.lookupBlacklist(TENANT_ID, token(), BlacklistEntry.Status.ACTIVE));
    }

    @Test
    void opaqueTokenIsDefensiveRedactedAndHasNoPublicRawAccessorOrSerializationContract() {
        byte[] digest = rawDigest();
        LegacyMobileLookupToken token = new LegacyMobileLookupToken(digest, INDEXES, INDEXES);
        digest[0] ^= 0x7f;
        byte[] packageCopy = token.copyDigestForLegacyRead();
        assertThat(packageCopy).containsExactly(rawDigest());
        packageCopy[1] ^= 0x7f;
        assertThat(token.copyDigestForLegacyRead()).containsExactly(rawDigest());
        assertThat(token.toString()).contains("[redacted]").doesNotContain(rawDigestHex(), MOBILE);
        assertThat(token).isNotInstanceOf(java.io.Serializable.class);
        assertThat(Arrays.stream(LegacyMobileLookupToken.class.getDeclaredMethods())
                .filter(method -> Modifier.isPublic(method.getModifiers())
                        && !method.getName().equals("toString"))
                .map(Method::getReturnType))
                .doesNotContain(byte[].class, String.class, BlindIndexPort.OrderedIndexes.class);
    }

    private BlindIndexLookupService service(BlacklistEntryRepository legacy) {
        return new BlindIndexLookupService(jdbc, legacy);
    }

    private void insertKey(long version, String state) {
        jdbc.update("INSERT INTO ycs_crypto_key_references VALUES (?, ?, ?)",
                "MOBILE_BLIND_INDEX", version, state);
    }

    private void insertBlacklist(long id, Long tenantId, String locator, String listType) {
        jdbc.update("""
                INSERT INTO blacklist_entries
                    (id, tenant_id, mobile_encrypted, mobile_hash, list_type, source, status)
                VALUES (?, ?, ?, ?, ?, 'MANUAL', 'ACTIVE')
                """, id, tenantId, repeated(0x71), locator, listType);
    }

    private void insertMetadata(long rowId,
                                VersionedBlindIndex index,
                                String status,
                                byte[] bindingDigest) {
        jdbc.update("""
                INSERT INTO ycs_crypto_blind_indexes
                    (target_type, legacy_row_id, field_id, key_purpose, key_version,
                     index_value, index_status, original_row_digest)
                VALUES ('BLACKLIST_ENTRY', ?, 'mobile', 'MOBILE_BLIND_INDEX', ?, ?, ?, ?)
                """, rowId, index.keyVersion(), index.canonicalValue(), status, bindingDigest);
    }

    private static BlacklistEntryRepository.LookupProjection projection(
            long id, Long tenantId, BlacklistEntry.ListType listType) {
        BlacklistEntryRepository.LookupProjection projection =
                mock(BlacklistEntryRepository.LookupProjection.class);
        when(projection.getId()).thenReturn(id);
        when(projection.getTenantId()).thenReturn(tenantId);
        when(projection.getListType()).thenReturn(listType);
        when(projection.getStatus()).thenReturn(BlacklistEntry.Status.ACTIVE);
        when(projection.getLegacyIndex()).thenReturn(rawDigestHex());
        return projection;
    }

    private static LegacyMobileLookupToken token() {
        return new LegacyMobileLookupToken(rawDigest(), INDEXES, INDEXES);
    }

    private static byte[] rawDigest() {
        try {
            return MessageDigest.getInstance("SHA-256")
                    .digest(MOBILE.getBytes(StandardCharsets.US_ASCII));
        } catch (Exception failure) {
            throw new AssertionError(failure);
        }
    }

    private static String rawDigestHex() {
        return java.util.HexFormat.of().formatHex(rawDigest());
    }

    private static byte[] sequence(int seed) {
        byte[] bytes = new byte[VersionedBlindIndex.HMAC_BYTES];
        Arrays.fill(bytes, (byte) seed);
        return bytes;
    }

    private static byte[] repeated(int seed) {
        byte[] bytes = new byte[32];
        Arrays.fill(bytes, (byte) seed);
        return bytes;
    }

    private static void assertSanitized(Runnable operation) {
        assertThatThrownBy(operation::run)
                .isInstanceOf(IllegalStateException.class)
                .hasMessage(BlindIndexLookupService.SANITIZED_FAILURE)
                .hasNoCause();
    }
}
