package com.ycsopen.sms.core.common.security.persistence;

import com.ycsopen.sms.core.common.security.envelope.EnvelopeCodec;
import com.ycsopen.sms.core.common.security.envelope.ProtectionContext;
import com.ycsopen.sms.core.common.security.key.BlindIndexPort;
import com.ycsopen.sms.core.common.security.key.KeyHealth;
import com.ycsopen.sms.core.common.security.key.KeyProtectionPort;
import com.ycsopen.sms.core.common.security.key.VersionedBlindIndex;
import com.ycsopen.sms.core.common.security.key.WrappedDataKey;
import com.ycsopen.sms.core.domain.entity.MessageTask;
import com.ycsopen.sms.core.repository.MessageTaskRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.HexFormat;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DataJpaTest
@ActiveProfiles("test")
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class MessageTaskProtectionAdapterTest {

    private static final String KEY_REFERENCE = "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk";
    private static final String MESSAGE_ID = "MSG_1700000000000_ABC12345";
    private static final String MOBILE = "13800138000";
    private static final VersionedBlindIndex RETIRING_INDEX =
            new VersionedBlindIndex(1, sequence(32, 11));
    private static final VersionedBlindIndex ACTIVE_INDEX =
            new VersionedBlindIndex(2, sequence(32, 31));

    @Autowired
    MessageTaskRepository messageTaskRepository;

    @Autowired
    JdbcTemplate jdbc;

    @Autowired
    PlatformTransactionManager transactionManager;

    @BeforeEach
    void resetSchema() {
        jdbc.update("DELETE FROM message_tasks");
        jdbc.execute("DROP TABLE IF EXISTS ycs_crypto_blind_indexes");
        jdbc.execute("DROP TABLE IF EXISTS ycs_crypto_key_references");
        jdbc.execute("""
                CREATE TABLE ycs_crypto_key_references (
                    purpose VARCHAR(48) NOT NULL,
                    key_version BIGINT NOT NULL,
                    key_state VARCHAR(24) NOT NULL,
                    PRIMARY KEY (purpose, key_version)
                )
                """);
        jdbc.execute("""
                CREATE TABLE ycs_crypto_blind_indexes (
                    blind_index_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    target_type VARCHAR(64) NOT NULL,
                    legacy_row_id BIGINT NOT NULL,
                    field_id VARCHAR(64) NOT NULL,
                    key_purpose VARCHAR(48) NOT NULL,
                    key_version BIGINT NOT NULL,
                    index_value VARCHAR(53) NOT NULL,
                    index_status VARCHAR(16) NOT NULL,
                    original_row_digest BINARY(32) NOT NULL,
                    UNIQUE (target_type, legacy_row_id, field_id, key_version)
                )
                """);
        insertKey(1, "RETIRING");
        insertKey(2, "ACTIVE");
    }

    @Test
    void preparesExactContextAndAtomicallyPersistsEnvelopeLocatorAndPerVersionIndexes() {
        RecordingKeyPort keyPort = new RecordingKeyPort();
        RecordingBlindIndexPort blindIndexPort = new RecordingBlindIndexPort();
        MessageTaskProtectionAdapter adapter = adapter(keyPort, blindIndexPort);

        PreparedMessageMobile prepared = adapter.prepare(17L, MESSAGE_ID, MOBILE);

        assertThat(keyPort.context).isEqualTo(new ProtectionContext(
                ProtectionContext.Purpose.DATABASE_FIELD,
                "crypto-storage-bootstrap", "message_tasks", "mobile_encrypted",
                "tenant:17", "message_id=" + MESSAGE_ID));
        assertThat(blindIndexPort.context).isEqualTo(new BlindIndexPort.Context(
                "MESSAGE_TASK", "mobile", BlindIndexPort.Purpose.MOBILE_ROUTING, "tenant:17"));
        assertThat(prepared.copyEnvelope()).hasSize(156);
        ProtectedFieldCodec verifier = new ProtectedFieldCodec(
                new EnvelopeCodec(), keyPort, new FixedSecureRandom(), KEY_REFERENCE);
        assertThat(verifier.unprotect(prepared.copyEnvelope(), keyPort.context,
                EnvelopeCodec.Target.DATABASE_FIELD))
                .containsExactly(MOBILE.getBytes(StandardCharsets.US_ASCII));
        assertThat(prepared.queryIndexes().values()).containsExactly(RETIRING_INDEX, ACTIVE_INDEX);
        assertThat(prepared.toString()).contains("[redacted]").doesNotContain(MOBILE,
                RETIRING_INDEX.canonicalValue(), ACTIVE_INDEX.canonicalValue());

        byte[] callerCopy = prepared.copyEnvelope();
        callerCopy[0] ^= 0x7f;
        assertThat(prepared.copyEnvelope()).startsWith((byte) 'Y', (byte) 'C', (byte) 'S', (byte) 'E');

        MessageTask saved = adapter.save(task(17L, MESSAGE_ID), prepared);

        byte[] storedEnvelope = jdbc.queryForObject(
                "SELECT mobile_encrypted FROM message_tasks WHERE id = ?",
                byte[].class, saved.getId());
        String locator = jdbc.queryForObject(
                "SELECT mobile_hash FROM message_tasks WHERE id = ?",
                String.class, saved.getId());
        assertThat(storedEnvelope).containsExactly(prepared.copyEnvelope());
        assertThat(locator).matches("[a-f0-9]{64}").isNotEqualTo(rawMobileSha256());
        assertThat(jdbc.queryForList("""
                        SELECT key_version, index_value, index_status
                        FROM ycs_crypto_blind_indexes
                        ORDER BY key_version
                        """))
                .containsExactly(
                        java.util.Map.of("KEY_VERSION", 1L,
                                "INDEX_VALUE", RETIRING_INDEX.canonicalValue(),
                                "INDEX_STATUS", "RETIRING"),
                        java.util.Map.of("KEY_VERSION", 2L,
                                "INDEX_VALUE", ACTIVE_INDEX.canonicalValue(),
                                "INDEX_STATUS", "ACTIVE"));
        assertThat(jdbc.queryForObject(
                "SELECT OCTET_LENGTH(original_row_digest) FROM ycs_crypto_blind_indexes LIMIT 1",
                Integer.class)).isEqualTo(32);
    }

    @Test
    void rejectsInvalidIdentityCapacityAndDependencyOutageBeforeAnyWrite() {
        RecordingKeyPort keyPort = new RecordingKeyPort();
        RecordingBlindIndexPort blindIndexPort = new RecordingBlindIndexPort();
        MessageTaskProtectionAdapter adapter = adapter(keyPort, blindIndexPort);

        assertThatThrownBy(() -> adapter.prepare(0L, MESSAGE_ID, MOBILE))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> adapter.prepare(17L, "not-generated", MOBILE))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> adapter.prepare(17L, MESSAGE_ID, "1380013800"))
                .isInstanceOf(IllegalArgumentException.class);

        keyPort.unavailable = true;
        assertThatThrownBy(() -> adapter.prepare(17L, MESSAGE_ID, MOBILE))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage(MessageTaskProtectionAdapter.SANITIZED_FAILURE);

        keyPort.unavailable = false;
        blindIndexPort.unavailable = true;
        assertThatThrownBy(() -> adapter.prepare(17L, MESSAGE_ID, MOBILE))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage(MessageTaskProtectionAdapter.SANITIZED_FAILURE);

        assertNoProtectedRows();
    }

    @Test
    void rejectsPreparedIdentityMismatchAndLegacyStringAssignmentsWithoutWriting() {
        MessageTaskProtectionAdapter adapter = adapter(
                new RecordingKeyPort(), new RecordingBlindIndexPort());
        PreparedMessageMobile prepared = adapter.prepare(17L, MESSAGE_ID, MOBILE);

        assertThatThrownBy(() -> adapter.save(task(18L, MESSAGE_ID), prepared))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage(MessageTaskProtectionAdapter.SANITIZED_FAILURE);

        MessageTask legacy = task(17L, MESSAGE_ID);
        assertThatThrownBy(() -> legacy.setMobileEncrypted(MOBILE))
                .isInstanceOf(IllegalStateException.class);
        assertThatThrownBy(() -> legacy.setMobileHash(rawMobileSha256()))
                .isInstanceOf(IllegalStateException.class);
        assertNoProtectedRows();
    }

    @Test
    void metadataFailureRollsBackBothTheTaskAndEveryEarlierIndexInsert() {
        MessageTaskProtectionAdapter adapter = adapter(
                new RecordingKeyPort(), new RecordingBlindIndexPort());
        PreparedMessageMobile prepared = adapter.prepare(17L, MESSAGE_ID, MOBILE);
        jdbc.update("DELETE FROM ycs_crypto_key_references WHERE key_version = 2");

        assertThatThrownBy(() -> adapter.save(task(17L, MESSAGE_ID), prepared))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage(MessageTaskProtectionAdapter.SANITIZED_FAILURE)
                .hasNoCause();

        assertNoProtectedRows();
    }

    private MessageTaskProtectionAdapter adapter(KeyProtectionPort keyPort,
                                                 BlindIndexPort blindIndexPort) {
        ProtectedFieldCodec fieldCodec = new ProtectedFieldCodec(
                new EnvelopeCodec(), keyPort, new FixedSecureRandom(), KEY_REFERENCE);
        return new MessageTaskProtectionAdapter(
                fieldCodec, blindIndexPort, messageTaskRepository,
                new BlindIndexMetadataRepository(jdbc), new FixedSecureRandom(), transactionManager);
    }

    private void assertNoProtectedRows() {
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM message_tasks", Long.class)).isZero();
        assertThat(jdbc.queryForObject(
                "SELECT COUNT(*) FROM ycs_crypto_blind_indexes", Long.class)).isZero();
    }

    private void insertKey(long version, String state) {
        jdbc.update("""
                        INSERT INTO ycs_crypto_key_references (purpose, key_version, key_state)
                        VALUES ('MOBILE_BLIND_INDEX', ?, ?)
                        """, version, state);
    }

    private static MessageTask task(long tenantId, String messageId) {
        MessageTask task = new MessageTask();
        task.setMessageId(messageId);
        task.setTenantId(tenantId);
        task.setTemplateId(3L);
        task.setSignatureId(4L);
        task.setContent("synthetic-content");
        task.setSendStatus(MessageTask.SendStatus.PENDING);
        task.setChannelId(5L);
        task.setCost(BigDecimal.ZERO);
        return task;
    }

    private static String rawMobileSha256() {
        try {
            return HexFormat.of().formatHex(
                    MessageDigest.getInstance("SHA-256").digest(MOBILE.getBytes(StandardCharsets.US_ASCII)));
        } catch (Exception failure) {
            throw new AssertionError(failure);
        }
    }

    private static byte[] sequence(int length, int seed) {
        byte[] value = new byte[length];
        for (int index = 0; index < value.length; index++) {
            value[index] = (byte) (seed + index);
        }
        return value;
    }

    private static final class FixedSecureRandom extends SecureRandom {
        private int invocation;

        @Override
        public void nextBytes(byte[] bytes) {
            invocation++;
            for (int index = 0; index < bytes.length; index++) {
                bytes[index] = (byte) (invocation * 17 + index);
            }
        }
    }

    private static final class RecordingKeyPort implements KeyProtectionPort {
        private byte[] dataEncryptionKey;
        private ProtectionContext context;
        private boolean unavailable;

        @Override
        public WrappedDataKey wrap(byte[] dataEncryptionKey,
                                   byte[] authenticatedHeader,
                                   ProtectionContext semanticContext) {
            if (unavailable) {
                throw new IllegalStateException("provider detail must not escape");
            }
            this.dataEncryptionKey = dataEncryptionKey.clone();
            context = semanticContext;
            return new WrappedDataKey(KEY_REFERENCE, new byte[12], new byte[48]);
        }

        @Override
        public byte[] unwrap(WrappedDataKey wrappedDataKey,
                             byte[] authenticatedHeader,
                             ProtectionContext semanticContext) {
            return dataEncryptionKey.clone();
        }

        @Override
        public KeyHealth health() {
            return new KeyHealth(unavailable ? KeyHealth.Status.UNAVAILABLE : KeyHealth.Status.READY);
        }
    }

    private static final class RecordingBlindIndexPort implements BlindIndexPort {
        private Context context;
        private boolean unavailable;

        @Override
        public OrderedIndexes writeIndexes(String normalizedMobile, Context suppliedContext) {
            requireAvailable(normalizedMobile);
            context = suppliedContext;
            return new OrderedIndexes(List.of(RETIRING_INDEX, ACTIVE_INDEX));
        }

        @Override
        public OrderedIndexes queryIndexes(String normalizedMobile, Context suppliedContext) {
            requireAvailable(normalizedMobile);
            context = suppliedContext;
            return new OrderedIndexes(List.of(RETIRING_INDEX, ACTIVE_INDEX));
        }

        @Override
        public KeyHealth health() {
            return new KeyHealth(unavailable ? KeyHealth.Status.UNAVAILABLE : KeyHealth.Status.READY);
        }

        private void requireAvailable(String normalizedMobile) {
            if (unavailable || !MOBILE.equals(normalizedMobile)) {
                throw new IllegalStateException("index detail must not escape");
            }
        }
    }
}
