import { useEffect, useState } from 'react';
import ModalDialog from '@/components/common/ModalDialog';
import { createTenantAdministrator, listTenantAdministrators, updateTenantAdministrator, type TenantAdministrator } from '@/api/tenantAccessApi';
import '@/styles/tenant-access.css';
export default function TenantAdministratorsPage() {
 const [rows,setRows]=useState<TenantAdministrator[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [realName,setRealName]=useState(''); const [password,setPassword]=useState(''); const [userType,setUserType]=useState('TENANT_USER'); const [success,setSuccess]=useState('');
 const load=()=>{setLoading(true);setError(false);void listTenantAdministrators().then(v=>setRows(v??[])).catch(()=>setError(true)).finally(()=>setLoading(false));}; useEffect(load,[]);
 if(error)return <section data-testid="tenant-tenant-access-administrators-page"><p className="tenant-access-alert" data-testid="tenant-tenant-access-administrators-error">加载失败 <button data-testid="tenant-tenant-access-administrators-retry" onClick={load}>重试</button></p></section>;
 return <section data-testid="tenant-tenant-access-administrators-page"><div className="tenant-access-toolbar"><div><h1>子账号管理</h1><p className="page-description">仅管理本机构的业务和开发者账号。</p></div><button data-testid="tenant-tenant-access-administrators-create" onClick={()=>setOpen(true)}>新建子账号</button></div>
 {loading&&<p data-testid="tenant-tenant-access-administrators-loading">正在加载…</p>}{!loading&&!rows.length&&<p data-testid="tenant-tenant-access-administrators-empty">暂无子账号</p>}
 {!!rows.length&&<table className="ratio-table"><thead><tr><th>用户名</th><th>角色</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} data-testid="tenant-tenant-access-administrators-row" data-business-key={row.id}><td>{row.username}</td><td>{row.roleNames??row.userType}</td><td>{row.status}</td><td>{new Date(row.createdAt).toLocaleString()}</td><td><button data-testid="tenant-tenant-access-administrators-status-action" onClick={()=>void updateTenantAdministrator(row.id,{realName:row.realName,userType:row.userType,status:row.status==='ACTIVE'?'DISABLED':'ACTIVE'}).then(load)}>切换状态</button></td></tr>)}</tbody></table>}
 <p role="status">{success}</p>{open&&<ModalDialog labelledBy="tenant-admin-title" onRequestClose={()=>setOpen(false)}><div data-testid="tenant-tenant-access-administrators-create-dialog"><h2 id="tenant-admin-title">新建子账号</h2><div className="tenant-access-grid"><label>用户名<input data-testid="tenant-tenant-access-administrators-username-field" value={name} onChange={e=>setName(e.target.value)}/></label><label>显示名称<input value={realName} onChange={e=>setRealName(e.target.value)}/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>角色<select data-testid="tenant-tenant-access-administrators-role-field" value={userType} onChange={e=>setUserType(e.target.value)}><option value="TENANT_USER">业务用户</option><option value="TENANT_DEV">开发者</option></select></label></div><div className="tenant-access-actions"><button className="button-secondary" onClick={()=>setOpen(false)}>取消</button><button data-testid="tenant-tenant-access-administrators-role" onClick={()=>void createTenantAdministrator({username:name,password,realName,userType}).then(()=>{setOpen(false);setSuccess('创建成功');load();})}>创建</button></div></div></ModalDialog>}</section>;
}
