package com.ycsopen.sms.core.service.audit;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

class OperationAuditServiceTest {

    private OperationAuditService service;

    @BeforeEach
    void setUp() {
        JdbcTemplate jdbc = new JdbcTemplate(new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2).generateUniqueName(true).build());
        jdbc.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, username VARCHAR(50), user_type VARCHAR(20), tenant_id BIGINT)");
        jdbc.execute("""
                CREATE TABLE privileged_operation_audits (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actor_user_id BIGINT, actor_username VARCHAR(50), actor_user_type VARCHAR(20),
                    tenant_id BIGINT, operation VARCHAR(255), resource_type VARCHAR(64),
                    resource_id VARCHAR(128), request_method VARCHAR(8), route_template VARCHAR(255),
                    sanitized_request VARCHAR(4000), result_code VARCHAR(32), response_status INT,
                    client_ip VARCHAR(45), trace_id VARCHAR(32), latency_ms BIGINT,
                    occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.update("INSERT INTO users(id, username, user_type, tenant_id) VALUES (7, 'operator', 'OPERATOR', 9)");
        service = new OperationAuditService(jdbc);
    }

    @Test
    void appendsCompleteRedactedRecordAndAppliesActorScope() {
        long id = service.append(new OperationAuditService.AuditCommand(
                7L, "PUT /api/v1/console/platform-roles/{roleId}/permissions", "CONSOLE_HTTP",
                "roleId=12", "PUT", "/api/v1/console/platform-roles/{roleId}/permissions",
                "{\"fields\":{\"password\":\"[redacted]\"}}", "SUCCESS", 200,
                "192.0.2.9", "0123456789abcdef0123456789abcdef", 17));

        OperationAuditService.AuditPage own = service.search(
                new OperationAuditService.Search("operator", "platform-roles", "SUCCESS",
                        null, null, 0, 20), 7L);
        OperationAuditService.AuditPage other = service.search(
                new OperationAuditService.Search(null, null, null, null, null, 0, 20), 8L);

        assertThat(id).isPositive();
        assertThat(own.totalElements()).isOne();
        assertThat(own.items().getFirst().actor()).isEqualTo("operator");
        assertThat(own.items().getFirst().tenantId()).isEqualTo(9L);
        assertThat(own.items().getFirst().resource()).isEqualTo("CONSOLE_HTTP:roleId=12");
        assertThat(own.items().getFirst().requestSummary()).doesNotContain("never-store-this");
        assertThat(other.totalElements()).isZero();
    }

    @Test
    void startsAuditBeforeOperationAndFinalizesItsOutcome() {
        long id = service.start(new OperationAuditService.AuditCommand(
                7L, "POST /api/v1/console/example", "CONSOLE_HTTP", null,
                "POST", "/api/v1/console/example", "{\"fields\":{}}",
                "SUCCESS", 200, "192.0.2.9", null, 99));

        assertThat(service.search(new OperationAuditService.Search(
                null, null, "STARTED", null, null, 0, 20), null).totalElements()).isOne();
    }

    @Test
    void finalizesThroughTheDefinerProcedureInsteadOfDirectTableUpdate() {
        JdbcTemplate jdbc = mock(JdbcTemplate.class);
        OperationAuditService audited = new OperationAuditService(jdbc);

        audited.complete(91L, "CLIENT_FAILURE", 400, 17);

        verify(jdbc).update("CALL finalize_privileged_operation_audit(?, ?, ?, ?)",
                91L, "CLIENT_FAILURE", 400, 17L);
    }
}
