package com.ycsopen.sms.core.service.audit;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class SecurityEventServiceTest {

    private JdbcTemplate jdbc;
    private SecurityEventService service;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2)
                .generateUniqueName(true)
                .build();
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE security_events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_type VARCHAR(40) NOT NULL,
                    actor_user_id BIGINT,
                    tenant_id BIGINT,
                    result_code VARCHAR(32) NOT NULL,
                    client_ip VARCHAR(45),
                    trace_id VARCHAR(32),
                    safe_summary VARCHAR(255) NOT NULL,
                    source_digest VARCHAR(64) NOT NULL,
                    dedup_key VARCHAR(100) NOT NULL UNIQUE,
                    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        service = new SecurityEventService(jdbc);
    }

    @Test
    void bulkExportUsesThresholdAndExactIdempotency() {
        assertThat(service.recordBulkExport(7L, 9L, 41L, 999,
                SecurityEventService.SecurityEventResult.SUCCESS,
                "192.0.2.8", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")).isEmpty();

        long first = service.recordBulkExport(7L, 9L, 42L, 1000,
                SecurityEventService.SecurityEventResult.SUCCESS,
                "192.0.2.8", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa").orElseThrow();
        long retry = service.recordBulkExport(7L, 9L, 42L, 1000,
                SecurityEventService.SecurityEventResult.SUCCESS,
                "192.0.2.8", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa").orElseThrow();

        assertThat(retry).isEqualTo(first);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM security_events", Integer.class)).isOne();
        String stored = jdbc.queryForObject("SELECT CONCAT(safe_summary, source_digest, dedup_key) FROM security_events", String.class);
        assertThat(stored).doesNotContain("export-task:42");
    }

    @Test
    void conflictingDuplicateIsRejected() {
        service.recordBulkExport(7L, 9L, 42L, 1000,
                SecurityEventService.SecurityEventResult.SUCCESS,
                "192.0.2.8", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");

        assertThatThrownBy(() -> service.recordBulkExport(8L, 9L, 42L, 1000,
                SecurityEventService.SecurityEventResult.SUCCESS,
                "192.0.2.8", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("deduplication conflict");

        assertThatThrownBy(() -> service.recordBulkExport(7L, 9L, 42L, 5000,
                SecurityEventService.SecurityEventResult.SUCCESS,
                "192.0.2.8", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("deduplication conflict");
    }

    @Test
    void repeatedFailureAndUnusualLoginAreAttributableAndDeduplicated() {
        service.recordRepeatedLoginFailure(7L, 9L, 501L, "192.0.2.8", null);
        service.recordRepeatedLoginFailure(7L, 9L, 501L, "192.0.2.8", null);
        service.recordUnusualLogin(7L, 9L, "session-secret", "192.0.2.9", null);
        service.recordUnusualLogin(7L, 9L, "session-secret", "192.0.2.9", null);

        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM security_events", Integer.class)).isEqualTo(2);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM security_events WHERE actor_user_id=7 AND tenant_id=9", Integer.class)).isEqualTo(2);
        String stored = jdbc.queryForObject("SELECT LISTAGG(source_digest || dedup_key || safe_summary, '') FROM security_events", String.class);
        assertThat(stored).doesNotContain("session-secret");
    }
}
