package com.ycsopen.sms.core.service.tenant;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.ycsopen.sms.core.common.exception.BusinessException;
import com.ycsopen.sms.core.service.audit.OperationAuditService;
import com.ycsopen.sms.core.web.dto.TenantApiKeyCreateRequest;
import com.ycsopen.sms.core.web.dto.TenantApiKeyAuditResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.time.LocalDateTime;
import java.util.ArrayList;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/** OBL-F-2-6-A/B lifecycle, tenant isolation, audit, and secret projection checks. */
class TenantApiKeyServiceTest {
    private TenantApiKeyService service;

    @BeforeEach
    void setUp() {
        JdbcTemplate jdbc = new JdbcTemplate(new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2).generateUniqueName(true).build());
        jdbc.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, username VARCHAR(50), user_type VARCHAR(20), tenant_id BIGINT)");
        jdbc.execute("""
                CREATE TABLE tenant_api_keys (
                    id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, app_key VARCHAR(64) NOT NULL,
                    app_secret_encrypted VARBINARY(512) NOT NULL, key_name VARCHAR(64) NOT NULL,
                    description VARCHAR(255), status VARCHAR(20) NOT NULL, ip_whitelist VARCHAR(1000),
                    rate_limit_per_sec INT, rate_limit_per_min INT, rate_limit_per_hour INT,
                    rate_limit_per_day INT, expire_time TIMESTAMP, last_used_time TIMESTAMP,
                    revoked_at TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE privileged_operation_audits (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actor_user_id BIGINT, actor_username VARCHAR(50), actor_user_type VARCHAR(20),
                    tenant_id BIGINT, operation VARCHAR(255), resource_type VARCHAR(64),
                    resource_id VARCHAR(128), request_method VARCHAR(8), route_template VARCHAR(255),
                    sanitized_request VARCHAR(4000), result_code VARCHAR(32), response_status INT,
                    client_ip VARCHAR(45), trace_id VARCHAR(32), latency_ms BIGINT,
                    occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.update("INSERT INTO users VALUES (11, 'tenant-a-admin', 'TENANT_ADMIN', 100)");
        jdbc.update("INSERT INTO users VALUES (12, 'tenant-a-dev', 'TENANT_DEV', 100)");
        jdbc.update("INSERT INTO users VALUES (21, 'tenant-b-admin', 'TENANT_ADMIN', 200)");
        jdbc.update("INSERT INTO users VALUES (31, 'tenant-a-user', 'TENANT_USER', 100)");
        TenantCredentialSecretProtectionService protection = mock(TenantCredentialSecretProtectionService.class);
        when(protection.protect(anyLong(), anyLong(), anyString(), any(char[].class)))
                .thenReturn(new byte[]{1, 2, 3, 4});
        service = new TenantApiKeyService(jdbc, protection, new OperationAuditService(jdbc),
                mock(ApplicationEventPublisher.class));
    }

    @Test
    void createListRevokeAndAuditAreTenantScopedAndSecretSafe() throws Exception {
        var request = new TenantApiKeyCreateRequest("integration", "synthetic",
                LocalDateTime.now().plusDays(1), "127.0.0.1/32, 2001:db8::/32", 10, 100, 1_000, 10_000);

        var created = service.create(11L, request);
        String plaintext = created.appSecret();

        assertThat(plaintext).isNotBlank();
        assertThat(created.appSecretMask()).isEqualTo("******");
        assertThat(created.toString()).doesNotContain(plaintext);
        assertThat(new ObjectMapper().findAndRegisterModules().writeValueAsString(created))
                .contains("\"appSecret\"").contains(plaintext);

        assertThat(service.list(12L)).singleElement().satisfies(row -> {
            assertThat(row.appSecretMask()).isEqualTo("******");
            assertThat(row.appSecret()).isNull();
            assertThat(row.ipWhitelist()).isEqualTo("[\"127.0.0.1/32\",\"2001:db8::/32\"]");
            assertThat(row.toString()).doesNotContain(plaintext);
        });
        assertThat(new ObjectMapper().findAndRegisterModules().writeValueAsString(service.list(12L)))
                .doesNotContain("appSecret\"").doesNotContain(plaintext);
        assertThat(service.list(21L)).isEmpty();
        assertThatThrownBy(() -> service.revoke(21L, created.id()))
                .isInstanceOf(BusinessException.class).hasMessage("凭证不存在或已停用");

        service.revoke(11L, created.id());

        assertThat(service.list(11L)).singleElement()
                .extracting(row -> row.status()).isEqualTo("DISABLED");
        assertThat(service.auditTrail(11L))
                .extracting(audit -> audit.operation())
                .containsExactly("TENANT_API_KEY_REVOKE", "TENANT_API_KEY_CREATE");
        assertThat(service.auditTrail(11L).toString()).doesNotContain(plaintext);
        assertThat(TenantApiKeyAuditResponse.class.getRecordComponents())
                .extracting(component -> component.getName())
                .containsExactly("id", "actor", "operation", "resourceId", "result", "occurredAt");
        var auditJson = new ObjectMapper().findAndRegisterModules().readTree(
                new ObjectMapper().findAndRegisterModules().writeValueAsString(service.auditTrail(11L))).get(0);
        var auditFields = new ArrayList<String>();
        auditJson.fieldNames().forEachRemaining(auditFields::add);
        assertThat(auditFields).containsExactly(
                "id", "actor", "operation", "resourceId", "result", "occurredAt");
        assertThat(auditJson.toString()).doesNotContain(
                plaintext, "appSecret", "sanitizedRequest", "clientIp", "traceId", "tenantId");
        assertThat(service.auditTrail(21L)).isEmpty();
    }

    @Test
    void requestCannotSelectTenantAndTenantUserCannotReadCredentialsOrAudits() {
        var request = new TenantApiKeyCreateRequest("integration", "synthetic",
                LocalDateTime.now().plusDays(1), "127.0.0.1/32", 10, 100, 1_000, 10_000);

        assertThat(TenantApiKeyCreateRequest.class.getRecordComponents())
                .extracting(component -> component.getName()).doesNotContain("tenantId", "secret");
        assertThatThrownBy(() -> service.list(31L))
                .isInstanceOf(BusinessException.class).hasMessage("无权执行此操作");
        assertThatThrownBy(() -> service.auditTrail(31L))
                .isInstanceOf(BusinessException.class).hasMessage("无权执行此操作");
        assertThat(request.perDay()).isEqualTo(10_000);
    }

    @Test
    void rejectsWhitelistRulesThatAuthenticationCannotEvaluate() {
        var invalidIpv4 = new TenantApiKeyCreateRequest("invalid-ipv4", "synthetic",
                LocalDateTime.now().plusDays(1), "999.0.0.1/24", 10, 100, 1_000, 10_000);
        var invalidIpv6Prefix = new TenantApiKeyCreateRequest("invalid-ipv6", "synthetic",
                LocalDateTime.now().plusDays(1), "2001:db8::/129", 10, 100, 1_000, 10_000);

        assertThatThrownBy(() -> service.create(11L, invalidIpv4))
                .isInstanceOf(BusinessException.class).hasMessage("凭证策略不合法");
        assertThatThrownBy(() -> service.create(11L, invalidIpv6Prefix))
                .isInstanceOf(BusinessException.class).hasMessage("凭证策略不合法");
    }
}
